<div id="frontadmin-nav-bar">
	<?php echo $this->getMenuLevel($this->getMenuArray()); ?>
	<ul id="ext-nav">
		<li id="flush-allcache-link" >
			<a href="<?php echo $this->_url->getUrl('frontadmin/index/flushAll'); ?>">
				<span><?php echo $this->__('Flush Cache Storage') ?></span>
			</a>
		</li>

		<?php if(Mage::getSingleton('core/session')->getEditUrl()) : ?>
		<li id="page-edit-link" >
			<a target="_blank" href="<?php echo Mage::getSingleton('core/session')->getEditUrl() ?>">
				<span><?php echo $this->__('Edit') ?></span>
			</a>
		</li>
		<?php endif; ?>
	</ul>
</div>

<div id="frontadmin-please-wait" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/frontadmin/ajax-loader-tr.gif') ?>" alt="<?php echo $this->__('Loading...') ?>"/><br/><?php echo $this->__('Please wait...') ?></p>
</div>

<script type="text/javascript">

	var flush_allcache_link = $('flush-allcache-link').querySelector('a');
	var flush_allcache_function = function ()
    {
    	var url = flush_allcache_link.href;
        new Ajax.Request(url, {
            parameters: {isAjax: 1, method: 'POST'},
            onLoading: function(){$('frontadmin-please-wait').show();},
            onSuccess: function(transport) {
                window.location.reload();
            }
        });
        return false;
    }

	Event.observe(flush_allcache_link, 'click', flush_allcache_function);

</script>